// import {WHITE} from '@theme';
// import {ligh_green} from '@utils';
import {StyleSheet} from 'react-native';
// import {colorRedDC143C} from './appTheme';
import {RFValue as RF} from 'react-native-responsive-fontsize';

export const GST = StyleSheet.create({
  loader: {
    flex: 1,
    marginTop: RF(20),
    marginLeft: RF(20),
  },
  bgBlack: {backgroundColor: 'black'},
  white: {color: 'white'},
  // greenClr: {color: ligh_green},
  flex9: {flex: 0.9},
  mb5: {marginBottom: '5%'},
  mt40: {marginTop: RF(40)},
  aI_End: {alignItems: 'flex-end'},
  mb7: {marginBottom: RF(7)},
  pb40: {paddingBottom: RF(50)},
  flexColumn: {flexDirection: 'column'},
  h40: {height: RF(40)},
  mh10: {marginHorizontal: RF(10)},
  mH10: {marginHorizontal: -RF(15)},
  mR5: {marginRight: RF(5)},
  //   clr: {color: colorRedDC143C},
  flexCol: {flexDirection: 'column'},
  br15: {borderRadius: 15},
  flexHalf: {flex: 0.5},
  fieldSpace: {flex: 0.5, marginLeft: RF(10)},
  flexRow: {flexDirection: 'row', flex: 1},
  flex: {flex: 1},
  flexDir: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  flexDir1: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heartImg: {
    width: RF(22.5),
    height: RF(20),
  },
  AIC: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mLeft: {
    marginLeft: RF(10),
  },
  mLeft30: {
    marginLeft: RF(30),
  },
  mLeft5: {
    marginLeft: RF(5),
  },
  mt1: {
    marginTop: RF(4),
  },
  mt10: {marginTop: RF(10)},
  mt15: {
    marginTop: RF(15),
  },
  mt20: {
    marginTop: RF(20),
  },
  AI: {
    alignItems: 'center',
  },
  hitSlop: {
    top: 10,
    bottom: 10,
    left: 10,
    right: 10,
  },
  PH: {paddingHorizontal: 0},
  // BC: {backgroundColor: WHITE},
  PH15: {paddingHorizontal: RF(15)},
  mb1: {
    marginBottom: RF(5),
  },
  pb2: {paddingBottom: RF(2)},
  mb10: {marginBottom: RF(5)},
  mV1: {
    marginVertical: RF(5),
  },
  mb25: {marginBottom: RF(25)},
  pb: {paddingBottom: RF(20)},
  pb35: {paddingBottom: RF(35)},
  pt: {paddingTop: RF(20)},
  mH: {marginHorizontal: RF(15)},
  mh25: {marginHorizontal: -RF(25)},
  mR: {marginRight: RF(15)},
  mR10: {marginRight: RF(10)},
  mh5: {marginHorizontal: RF(5)},
  ml80: {marginLeft: RF(80)},
  ml3: {marginLeft: '3%'},
  ph5: {paddingHorizontal: RF(5)},
  // bgW: {backgroundColor: WHITE},
  pV15: {paddingVertical: RF(15)},
  pv20: {paddingVertical: 10},
  mt5: {marginTop: RF(5)},
  LG: {
    position: 'absolute',
    borderRadius: RF(10),
    height: RF(200),
    width: RF(150),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: RF(10),
  },
  pl15: {paddingLeft: RF(15)},
  flexJus: {flexDirection: 'row', justifyContent: 'space-evenly'},
  height: {height: '27%'},
  bR: {borderRadius: RF(10)},
  bR20: {borderRadius: RF(20)},
  wd: {width: '95%'},
  mv10: {marginVertical: RF(10)},
  mv20: {marginVertical: RF(20)},
  mt30: {marginTop: RF(30)},
  pl5: {paddingRight: RF(5)},
  pR5: {paddingRight: RF(5)},
  wd100: {width: '100%'},
  mt2: {marginTop: RF(2)},
});
